apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-proxy-port80
  labels:
    app: voting-app-proxy-port80
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-proxy-port80
  template:
    metadata:
      labels:
        app: voting-app-proxy-port80
    spec:
      containers:
      - name: nginx-proxy
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: proxy-config-port80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config-port80
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream voting_app {
            server 127.0.0.1:31514;
        }
        server {
            listen 80;
            server_name _;
            
            # Health check endpoint for Traffic Manager
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            # Proxy all other requests to the voting app
            location / {
                proxy_pass http://voting_app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 5s;
                proxy_send_timeout 5s;
                proxy_read_timeout 5s;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-proxy-port80
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # External access on port 30080
  selector:
    app: voting-app-proxy-port80