apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-proxy-8080
  labels:
    app: voting-app-proxy-8080
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-proxy-8080
  template:
    metadata:
      labels:
        app: voting-app-proxy-8080
    spec:
      containers:
      - name: nginx-proxy
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: proxy-config-8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config-8080
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream voting_app {
            server 127.0.0.1:31514;
        }
        server {
            listen 80;
            location / {
                proxy_pass http://voting_app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_connect_timeout 5s;
                proxy_send_timeout 5s;
                proxy_read_timeout 5s;
            }
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-proxy-8080
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30808  # Maps to external port 8080 via router
  selector:
    app: voting-app-proxy-8080