apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-enhanced-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-debug
  template:
    metadata:
      labels:
        app: voting-app-debug
    spec:
      containers:
      - name: voting-app
        image: python:3.9-slim
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "voting"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres123"
        - name: AZURE_API_URL
          value: "http://172.169.25.121/api/local-results"
        - name: DEBUG_MODE
          value: "true"
        command: ["/bin/sh"]
        args:
          - -c
          - |
            pip install flask psycopg2-binary requests
            cat > /app.py << 'EOF'
            from flask import Flask, render_template, request, jsonify
            import psycopg2
            import requests
            import json
            import os
            import time
            import logging

            # Enhanced logging
            logging.basicConfig(level=logging.DEBUG)
            logger = logging.getLogger(__name__)

            app = Flask(__name__)

            def get_db_connection():
                try:
                    return psycopg2.connect(
                        host=os.environ['DB_HOST'],
                        database=os.environ['DB_NAME'],
                        user=os.environ['DB_USER'],
                        password=os.environ['DB_PASSWORD']
                    )
                except Exception as e:
                    logger.error(f"DB connection error: {e}")
                    return None

            def get_azure_votes_enhanced():
                """Enhanced Azure API call with detailed logging"""
                azure_url = os.environ.get('AZURE_API_URL')
                logger.info(f"🔍 Attempting Azure API call to: {azure_url}")
                
                try:
                    # Multiple attempts with different timeouts
                    for attempt in range(3):
                        logger.info(f"🔄 Attempt {attempt + 1}/3")
                        
                        response = requests.get(
                            azure_url,
                            timeout=30,
                            headers={
                                'Accept': 'application/json',
                                'User-Agent': 'OnPrem-VotingApp/1.0'
                            }
                        )
                        
                        logger.info(f"📊 Response status: {response.status_code}")
                        logger.info(f"📊 Response headers: {dict(response.headers)}")
                        logger.info(f"📊 Raw response text: {response.text}")
                        
                        if response.status_code == 200:
                            data = response.json()
                            logger.info(f"📊 Parsed JSON: {data}")
                            
                            # Handle different response formats
                            if 'votes' in data:
                                votes = data['votes']
                                result = {
                                    'cat': votes.get('cat', 0),
                                    'dog': votes.get('dog', 0)
                                }
                                logger.info(f"✅ Extracted votes: {result}")
                                return result
                            else:
                                logger.warning(f"⚠️ Unexpected format: {data}")
                                return {'cat': 0, 'dog': 0}
                        
                        if attempt < 2:  # Don't sleep on last attempt
                            time.sleep(5)
                    
                    logger.error("❌ All attempts failed")
                    return {'cat': 0, 'dog': 0}
                    
                except requests.exceptions.Timeout:
                    logger.error("⏰ Request timeout")
                    return {'cat': 0, 'dog': 0}
                except requests.exceptions.ConnectionError as e:
                    logger.error(f"🔌 Connection error: {e}")
                    return {'cat': 0, 'dog': 0}
                except Exception as e:
                    logger.error(f"💥 Unexpected error: {e}")
                    return {'cat': 0, 'dog': 0}

            @app.route('/debug-azure')
            def debug_azure():
                """Detailed Azure API debugging endpoint"""
                azure_url = os.environ.get('AZURE_API_URL')
                debug_info = {
                    'azure_url': azure_url,
                    'timestamp': time.time()
                }
                
                try:
                    # Test basic connectivity
                    response = requests.get(azure_url, timeout=10)
                    debug_info['status_code'] = response.status_code
                    debug_info['response_text'] = response.text
                    debug_info['headers'] = dict(response.headers)
                    
                    if response.status_code == 200:
                        data = response.json()
                        debug_info['parsed_json'] = data
                        debug_info['extracted_votes'] = get_azure_votes_enhanced()
                    
                except Exception as e:
                    debug_info['error'] = str(e)
                
                return jsonify(debug_info)

            @app.route('/api/results')
            def get_results():
                """Get combined voting results with enhanced debugging"""
                logger.info("🎯 Getting combined results...")
                
                # Get local votes
                conn = get_db_connection()
                local_votes = {'cat': 0, 'dog': 0}
                
                if conn:
                    try:
                        with conn.cursor() as cursor:
                            # Try both column names for compatibility
                            try:
                                cursor.execute("SELECT vote_choice, COUNT(*) FROM votes GROUP BY vote_choice")
                            except:
                                cursor.execute("SELECT vote_option, COUNT(*) FROM votes GROUP BY vote_option")
                            
                            for vote_type, count in cursor.fetchall():
                                if vote_type.lower() in ['cat', 'cats']:
                                    local_votes['cat'] = count
                                elif vote_type.lower() in ['dog', 'dogs']:
                                    local_votes['dog'] = count
                        conn.close()
                    except Exception as e:
                        logger.error(f"Local DB error: {e}")

                # Get Azure votes with enhanced logging
                azure_votes = get_azure_votes_enhanced()
                
                result = {
                    'cat': {
                        'azure': azure_votes['cat'],
                        'onprem': local_votes['cat']
                    },
                    'dog': {
                        'azure': azure_votes['dog'], 
                        'onprem': local_votes['dog']
                    },
                    '_debug': {
                        'azure_raw': azure_votes,
                        'local_raw': local_votes,
                        'timestamp': time.time()
                    }
                }
                
                logger.info(f"📊 Final result: {result}")
                return jsonify(result)

            @app.route('/health')
            def health():
                return jsonify({'status': 'healthy', 'debug_mode': True})

            @app.route('/')
            def index():
                return '''
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Enhanced Debug Voting App</title>
                    <style>
                        body { font-family: Arial; margin: 40px; background: linear-gradient(135deg, #2e8b57, #90ee90); }
                        .container { background: white; padding: 20px; border-radius: 10px; max-width: 600px; }
                        .debug { background: #f0f0f0; padding: 15px; margin: 10px 0; border-radius: 5px; }
                        button { padding: 10px 20px; margin: 5px; border: none; border-radius: 5px; cursor: pointer; }
                        .vote-btn { background: #4CAF50; color: white; }
                        .debug-btn { background: #2196F3; color: white; }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <h1>🐱🐶 Enhanced Debug Voting App</h1>
                        
                        <div class="debug">
                            <h3>🔍 Debug Information</h3>
                            <p>Azure API URL: ''' + os.environ.get('AZURE_API_URL', 'Not set') + '''</p>
                            <p>Debug Mode: Enabled</p>
                            <button class="debug-btn" onclick="location.href='/debug-azure'">Test Azure API</button>
                            <button class="debug-btn" onclick="location.href='/api/results'">Get Results</button>
                        </div>
                        
                        <div id="results"></div>
                        
                        <script>
                            function loadResults() {
                                fetch('/api/results')
                                    .then(r => r.json())
                                    .then(data => {
                                        document.getElementById('results').innerHTML = 
                                            '<h3>📊 Current Results</h3>' +
                                            '<p>🐱 Cats: Azure=' + data.cat.azure + ', OnPrem=' + data.cat.onprem + ', Total=' + (data.cat.azure + data.cat.onprem) + '</p>' +
                                            '<p>🐶 Dogs: Azure=' + data.dog.azure + ', OnPrem=' + data.dog.onprem + ', Total=' + (data.dog.azure + data.dog.onprem) + '</p>' +
                                            '<pre>Debug: ' + JSON.stringify(data._debug, null, 2) + '</pre>';
                                    });
                            }
                            
                            // Auto-refresh every 10 seconds
                            setInterval(loadResults, 10000);
                            loadResults();
                        </script>
                    </div>
                </body>
                </html>
                '''

            if __name__ == '__main__':
                app.run(host='0.0.0.0', port=5000, debug=True)
            EOF
            
            python /app.py
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-debug-service
spec:
  selector:
    app: voting-app-debug
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31517
  type: NodePort