apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-azure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-azure
  template:
    metadata:
      labels:
        app: voting-app-azure
    spec:
      containers:
      - name: voting-app
        image: python:3.9-slim
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "voting"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres123"
        - name: AZURE_DB_HOST
          value: "postgres-cat-dog-voting.postgres.database.azure.com"
        - name: AZURE_DB_NAME
          value: "postgres"
        - name: AZURE_DB_USER
          value: "votinguser"
        - name: AZURE_DB_PASSWORD
          value: "SecureVotingPassword123!"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"  
            cpu: "300m"
        command: ["/bin/sh"]
        args:
          - -c
          - |
            pip install flask psycopg2-binary requests
            cat > /app.py << 'EOF'
            from flask import Flask, render_template, request, jsonify
            import psycopg2
            import os
            import logging
            import requests
            from datetime import datetime

            logging.basicConfig(level=logging.INFO)
            logger = logging.getLogger(__name__)

            app = Flask(__name__)

            def get_local_db_connection():
                """Get connection to local PostgreSQL database"""
                try:
                    return psycopg2.connect(
                        host=os.environ['DB_HOST'],
                        database=os.environ['DB_NAME'],
                        user=os.environ['DB_USER'],
                        password=os.environ['DB_PASSWORD']
                    )
                except Exception as e:
                    logger.error(f"Local DB connection error: {e}")
                    return None

            def get_azure_db_connection():
                """Get connection to Azure PostgreSQL database"""
                try:
                    conn = psycopg2.connect(
                        host=os.environ['AZURE_DB_HOST'],
                        database=os.environ['AZURE_DB_NAME'],
                        user=os.environ['AZURE_DB_USER'],
                        password=os.environ['AZURE_DB_PASSWORD'],
                        port=5432,
                        sslmode='require'
                    )
                    logger.info("✅ Azure PostgreSQL connection successful!")
                    return conn
                except Exception as e:
                    logger.error(f"Azure DB connection error: {e}")
                    return None

            def get_azure_votes_direct():
                """Get Azure votes directly from Azure PostgreSQL database"""
                conn = get_azure_db_connection()
                votes = {'cat': 0, 'dog': 0}

                if conn:
                    try:
                        with conn.cursor() as cursor:
                            # Query the vote_option table we created
                            cursor.execute("SELECT option, COUNT(*) FROM vote_option GROUP BY option")
                            for vote_type, count in cursor.fetchall():
                                if vote_type and vote_type.lower() in ['cat', 'cats']:
                                    votes['cat'] = count
                                elif vote_type and vote_type.lower() in ['dog', 'dogs']:
                                    votes['dog'] = count
                        conn.close()
                        logger.info(f"✅ Direct Azure DB votes: {votes}")
                    except Exception as e:
                        logger.error(f"Azure DB query error: {e}")
                        conn.close()

                return votes

            def get_local_votes():
                """Get local votes from on-premises database"""
                conn = get_local_db_connection()
                votes = {'cat': 0, 'dog': 0}

                if conn:
                    try:
                        with conn.cursor() as cursor:
                            # Try different column names
                            try:
                                cursor.execute("SELECT vote_choice, COUNT(*) FROM votes GROUP BY vote_choice")
                            except:
                                try:
                                    cursor.execute("SELECT vote_option, COUNT(*) FROM votes GROUP BY vote_option")
                                except:
                                    cursor.execute("SELECT option, COUNT(*) FROM votes GROUP BY option")
                            
                            for vote_type, count in cursor.fetchall():
                                if vote_type and vote_type.lower() in ['cat', 'cats']:
                                    votes['cat'] = count
                                elif vote_type and vote_type.lower() in ['dog', 'dogs']:
                                    votes['dog'] = count
                        conn.close()
                    except Exception as e:
                        logger.error(f"Local DB error: {e}")

                return votes

            @app.route('/api/results')
            def get_results():
                """API endpoint for getting cross-environment vote results"""
                
                # Get local votes
                local_votes = get_local_votes()
                
                # Get Azure votes directly from Azure database
                azure_votes = get_azure_votes_direct()
                
                # Calculate totals and percentages
                total_cat = azure_votes['cat'] + local_votes['cat']
                total_dog = azure_votes['dog'] + local_votes['dog']
                grand_total = total_cat + total_dog
                
                cat_percentage = (total_cat / grand_total * 100) if grand_total > 0 else 0
                dog_percentage = (total_dog / grand_total * 100) if grand_total > 0 else 0

                return jsonify({
                    'environment': 'onprem',
                    'timestamp': datetime.now().isoformat(),
                    'votes': {
                        'cat': {
                            'azure': azure_votes['cat'],
                            'onprem': local_votes['cat'],
                            'total': total_cat,
                            'percentage': round(cat_percentage, 2)
                        },
                        'dog': {
                            'azure': azure_votes['dog'],
                            'onprem': local_votes['dog'], 
                            'total': total_dog,
                            'percentage': round(dog_percentage, 2)
                        }
                    }
                })

            @app.route('/test-azure-db')
            def test_azure_db():
                """Test endpoint for Azure database connection"""
                try:
                    azure_votes = get_azure_votes_direct()
                    return jsonify({
                        'success': True,
                        'azure_votes': azure_votes,
                        'method': 'direct_database_connection'
                    })
                except Exception as e:
                    return jsonify({
                        'success': False,
                        'error': str(e),
                        'method': 'direct_database_connection'
                    })

            @app.route('/health')
            def health():
                return jsonify({
                    'status': 'healthy',
                    'mode': 'direct-azure-db',
                    'azure_db_host': os.environ.get('AZURE_DB_HOST')
                })

            @app.route('/vote', methods=['POST'])
            def vote():
                """Handle voting"""
                vote_data = request.get_json()
                if not vote_data or 'vote' not in vote_data:
                    return jsonify({'error': 'Invalid vote data'}), 400

                vote_choice = vote_data['vote'].lower()
                if vote_choice not in ['cat', 'dog']:
                    return jsonify({'error': 'Invalid vote choice'}), 400

                conn = get_local_db_connection()
                if conn:
                    try:
                        with conn.cursor() as cursor:
                            try:
                                cursor.execute("INSERT INTO votes (vote_choice) VALUES (%s)", (vote_choice,))
                            except:
                                cursor.execute("INSERT INTO votes (vote_option) VALUES (%s)", (vote_choice,))
                        conn.commit()
                        conn.close()
                        return jsonify({'success': True, 'vote': vote_choice})
                    except Exception as e:
                        logger.error(f"Vote insert error: {e}")
                        return jsonify({'error': str(e)}), 500

                return jsonify({'error': 'Database connection failed'}), 500

            @app.route('/')
            def index():
                return '''
                <!DOCTYPE html>
                <html>
                <head>
                    <title>🌐 Cross-Environment Voting App</title>
                    <style>
                        body { 
                            font-family: Arial, sans-serif; 
                            margin: 40px; 
                            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                            min-height: 100vh;
                        }
                        .container { 
                            background: white; 
                            padding: 30px; 
                            border-radius: 15px; 
                            max-width: 800px; 
                            margin: 0 auto;
                            box-shadow: 0 10px 30px rgba(0,0,0,0.3);
                        }
                        .header {
                            text-align: center;
                            margin-bottom: 30px;
                            background: linear-gradient(135deg, #667eea, #764ba2);
                            color: white;
                            padding: 20px;
                            border-radius: 10px;
                            margin: -30px -30px 30px -30px;
                        }
                        .success { 
                            background: linear-gradient(135deg, #56ab2f, #a8e6cf);
                            padding: 20px; 
                            margin: 15px 0; 
                            border-radius: 10px; 
                            color: white;
                            text-align: center;
                        }
                        .vote-section {
                            text-align: center;
                            margin: 30px 0;
                            padding: 20px;
                            background: #f8f9fa;
                            border-radius: 10px;
                        }
                        .vote-btn { 
                            font-size: 24px; 
                            padding: 20px 40px; 
                            margin: 10px; 
                            border: none; 
                            border-radius: 50px; 
                            cursor: pointer; 
                            background: linear-gradient(45deg, #667eea, #764ba2);
                            color: white;
                            transition: transform 0.2s;
                        }
                        .vote-btn:hover {
                            transform: scale(1.05);
                        }
                        .control-btn {
                            padding: 12px 25px;
                            margin: 5px;
                            border: none;
                            border-radius: 25px;
                            cursor: pointer;
                            background: #28a745;
                            color: white;
                            transition: background 0.3s;
                        }
                        .control-btn:hover {
                            background: #218838;
                        }
                        #results {
                            background: #f8f9fa;
                            padding: 20px;
                            border-radius: 10px;
                            margin: 20px 0;
                        }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <div class="header">
                            <h1>🐱🐶 Cross-Environment Voting App</h1>
                            <h2>🔗 Direct Azure Database Access</h2>
                        </div>

                        <div class="success">
                            <h3>✅ Direct Azure PostgreSQL Connection Active</h3>
                            <p>Real-time vote synchronization between On-Premises and Azure!</p>
                        </div>

                        <div class="vote-section">
                            <h3>🗳️ Cast Your Vote!</h3>
                            <button class="vote-btn" onclick="vote('cat')">🐱 Vote for Cats</button>
                            <button class="vote-btn" onclick="vote('dog')">🐶 Vote for Dogs</button>
                        </div>

                        <div style="text-align: center;">
                            <button class="control-btn" onclick="loadResults()">📊 Refresh Results</button>
                            <button class="control-btn" onclick="testAzureDb()">🧪 Test Azure DB</button>
                        </div>

                        <div id="results"></div>
                        <div id="azure-test"></div>

                        <script>
                            function vote(animal) {
                                fetch('/vote', {
                                    method: 'POST',
                                    headers: {'Content-Type': 'application/json'},
                                    body: JSON.stringify({vote: animal})
                                }).then(r => r.json()).then(data => {
                                    if (data.success) {
                                        loadResults();
                                        alert('✅ Vote recorded for ' + animal.toUpperCase() + '!');
                                    } else {
                                        alert('❌ Error recording vote');
                                    }
                                });
                            }

                            function testAzureDb() {
                                fetch('/test-azure-db')
                                    .then(r => r.json())
                                    .then(data => {
                                        document.getElementById('azure-test').innerHTML =
                                            '<div style="background: #e9ecef; padding: 15px; border-radius: 8px; margin: 15px 0;">' +
                                            '<h4>🔗 Azure Database Connection Test</h4>' +
                                            '<pre style="background: white; padding: 10px; border-radius: 5px;">' + 
                                            JSON.stringify(data, null, 2) + '</pre></div>';
                                    });
                            }

                            function loadResults() {
                                fetch('/api/results')
                                    .then(r => r.json())
                                    .then(data => {
                                        const votes = data.votes;
                                        document.getElementById('results').innerHTML =
                                            '<h3>📊 Live Cross-Environment Results</h3>' +
                                            '<div style="display: flex; gap: 20px; margin: 20px 0;">' +
                                            '<div style="flex: 1; text-align: center; background: #fff3cd; padding: 15px; border-radius: 8px;">' +
                                            '<h4>🐱 CATS</h4>' +
                                            '<div style="font-size: 24px; font-weight: bold; color: #856404;">' + votes.cat.total + '</div>' +
                                            '<div style="font-size: 14px;">Azure: ' + votes.cat.azure + ' | OnPrem: ' + votes.cat.onprem + '</div>' +
                                            '<div style="font-size: 14px; margin-top: 5px;">' + votes.cat.percentage + '%</div>' +
                                            '</div>' +
                                            '<div style="flex: 1; text-align: center; background: #d1ecf1; padding: 15px; border-radius: 8px;">' +
                                            '<h4>🐶 DOGS</h4>' +
                                            '<div style="font-size: 24px; font-weight: bold; color: #0c5460;">' + votes.dog.total + '</div>' +
                                            '<div style="font-size: 14px;">Azure: ' + votes.dog.azure + ' | OnPrem: ' + votes.dog.onprem + '</div>' +
                                            '<div style="font-size: 14px; margin-top: 5px;">' + votes.dog.percentage + '%</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '<p style="text-align: center; font-weight: bold; color: #495057;">🎉 Total Votes: ' + 
                                            (votes.cat.total + votes.dog.total) + ' across both environments!</p>' +
                                            '<p style="text-align: center; font-size: 12px; color: #6c757d;">Last updated: ' + 
                                            new Date(data.timestamp).toLocaleString() + '</p>';
                                    });
                            }

                            // Auto-refresh every 15 seconds
                            setInterval(loadResults, 15000);
                            loadResults();
                        </script>
                    </div>
                </body>
                </html>
                '''

            if __name__ == '__main__':
                logger.info("🎯 Starting enhanced cross-environment voting app in azure environment...")
                logger.info("🌐 Remote API: http://66.242.207.21:31514")
                logger.info("🗄️ Connecting to Azure PostgreSQL directly...")
                app.run(host='0.0.0.0', port=5000, debug=False)
            EOF

            python /app.py
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-azure-service-31514
spec:
  type: NodePort
  selector:
    app: voting-app-azure
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31514