apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-load-balancer
  labels:
    app: voting-load-balancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-load-balancer
  template:
    metadata:
      labels:
        app: voting-load-balancer
    spec:
      containers:
      - name: load-balancer
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi" 
            cpu: "100m"
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Create nginx configuration for load balancing with failover
            cat > /etc/nginx/nginx.conf << 'EOF'
            events {
                worker_connections 1024;
            }
            http {
                # Define upstream backends with health checks and failover
                upstream voting_backends {
                    # Azure backend (primary)
                    server 52.154.54.110:80 weight=3 max_fails=2 fail_timeout=30s;
                    # OnPrem backend (secondary) 
                    server 66.242.207.21:31514 weight=1 max_fails=2 fail_timeout=30s backup;
                }
                
                server {
                    listen 80;
                    
                    # Load balancer health check
                    location /health {
                        access_log off;
                        return 200 "Load Balancer OK";
                        add_header Content-Type text/plain;
                    }
                    
                    # Backend status endpoint
                    location /lb-status {
                        access_log off;
                        return 200 "Backends: Azure(52.154.54.110) + OnPrem(66.242.207.21:31514)";
                        add_header Content-Type text/plain;
                    }
                    
                    # Main application with failover
                    location / {
                        proxy_pass http://voting_backends;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_connect_timeout 5s;
                        proxy_send_timeout 30s;
                        proxy_read_timeout 30s;
                        
                        # Retry failed requests on next upstream
                        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
                        proxy_next_upstream_tries 2;
                        
                        # Add header to show load balancing is active
                        add_header X-Load-Balanced "true" always;
                    }
                }
            }
            EOF
            
            echo "ðŸ”„ Starting NGINX Load Balancer with Failover..."
            echo "ðŸŽ¯ Primary: Azure AKS (52.154.54.110) - Weight 3"
            echo "ðŸ”„ Backup: OnPrem K3s (66.242.207.21:31514) - Weight 1" 
            echo "â¤ï¸ Health Checks: 2 failures â†’ 30s timeout â†’ failover"
            echo "ðŸš€ Ready to serve traffic with automatic failover!"
            
            # Start nginx
            nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: voting-load-balancer-service
  labels:
    app: voting-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: voting-load-balancer